$:
  vscode:
  - services:
    - docker
    - vscode
    runner:
      cpus: 1
    stages:
      - name: update dependencies
        script: apt update
      - name: install dependencies
        script: apt install -y sudo
      - name: install fastfetch
        script: 
        - wget https://github.com/fastfetch-cli/fastfetch/releases/download/latest/fastfetch-linux-amd64.deb
        - dpkg -i fastfetch-linux-amd64.deb
        - rm fastfetch-linux-amd64.deb
        - fastfetch

main:
  push: 
    - runner: 
        cpus: 1
      imports: https://cnb.cool/BlueScreen-Studio/Tech/secrets/-/blob/sdcom/github.yml
      stages:
        - name: sync to github
          image: tencentcom/git-sync         
          settings:
            target_url: https://github.com/SDCOM-0415/shit.git
            auth_type: https
            username: ${GIT_USERNAME}
            password: ${GIT_ACCESS_TOKEN}
            git_user: ${GIT_USERNAME}
            git_email: ${GIT_EMAIL}
            force: true
            branch: main 
            sync_mode: push